accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),

    path('', views.dashboard, name='dashboard'),
    # path('my_orders/', views.my_orders, name='my_orders'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('change_password/', views.change_password, name='change_password'),
    path('order_detail/<int:order_id>/', views.order_detail, name='order_detail'),
    
    path('forget_password/', views.forget_password, name="forget_password"),
    path('resetpassword_validate/<uidb64>/<token>/', views.resetpassword_validate, name='resetpassword_validate'),
    path('reset_password/', views.reset_password, name="reset_password"),
]

app/urls.py
from django.urls import path
from . import views 

app_name = 'app'

urlpatterns = [
    path('about/', views.about, name='about'),
    path('contact/', views.contact_us, name='contact'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls', namespace='shop')),
    path('app/', include('app.urls', namespace='app')),
    path('account/', include('accounts.urls', namespace='accounts')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

store/urls.py
from django.urls import path
from django.utils.regex_helper import normalize
from . import views


app_name = 'shop'

urlpatterns = [
    path('', views.home, name='home'),
    path('shop/', views.shop, name='shop'),
    path('shop/<slug:category_slug>/', views.shop, name='categries'),
    path('shop/<slug:category_slug>/<slug:product_details_slug>/', views.product_details, name='product_details'),
    path('search/', views.search, name='search'),
    path('review/<int:product_id>/', views.review, name='review'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager

class AccountManger(BaseUserManager):
    def create_user(self, first_name, last_name, username, email, password=None):
        if not email :
            raise ValueError('User must have an email address')
        if not username :
            raise ValueError('User must have an username')

        user = self.model(
            # normalize_email => if as write captel char it turn for samll char
            email = self.normalize_email(email),
            first_name = first_name,
            last_name = last_name,
            username = username,
        )
        user.set_password(password)
        user.save(using=self._db)
        return user
    
    def create_superuser(self, first_name, last_name, username, email, password):
        user = self.create_user(
            email = self.normalize_email(email),
            first_name = first_name,
            last_name = last_name,
            username = username,
            password = password,
        )
        user.is_admin = True
        user.is_active = True
        user.is_staff = True
        user.is_superadmin = True
        
        user.save(using=self._db)
        return user

class Account(AbstractBaseUser):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    username = models.CharField(max_length=50, unique=True)
    email = models.EmailField(max_length=100, unique=True)
    Phone_number = models.CharField(max_length=50)

    # Required
    is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=False)
    is_superadmin = models.BooleanField(default=False)
    
    
    date_joined_for_format = models.DateTimeField(auto_now_add=True)
    last_login_for_format  = models.DateTimeField(auto_now_add=True)
    def date_joined(self):
        return self.date_joined_for_format.strftime('%B %d %Y')
    def last_login(self):
        return self.last_login_for_format.strftime('%B %d %Y')

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username', 'first_name', 'last_name']

    objects = AccountManger()

    def __str__(self):
        return self.email
    
    def full_name(self):
        return f'{self.first_name} {self.last_name}'

    # he has all the permission to do all the changes
    def has_perm(self, perm, obj=None):
        return self.is_admin

    def has_module_perms(self, add_label):
        return True


class UserProfile(models.Model):
    user = models.OneToOneField(Account, on_delete=models.CASCADE)
    address = models.TextField(blank=True, max_length=500)
    profile_picture = models.ImageField(blank=True, upload_to='userprofile',default='user_image_default.png')
    city = models.CharField(blank=True, max_length=20)
    state = models.CharField(blank=True, max_length=20)
    country = models.CharField(blank=True, max_length=20)

    def __str__(self):
        return self.user.first_name

accounts/forms.py
from django import forms
from .models import Account ,UserProfile

class RegisterationFrom(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        # 'placeholder' : 'Enter Password',
        'class' : 'form-control',
    }))
    repeat_password = forms.CharField(widget=forms.PasswordInput(attrs={
        # 'placeholder' : 'Repeate Password',
        'class' : 'form-control',
    }))
    class Meta:
        model = Account
        fields = ['first_name', 'last_name', 'Phone_number', 'email', 'password']

    def __init__(self, *args, **kwargs):
        super(RegisterationFrom, self).__init__(*args, **kwargs)
        # self.fields['first_name'].widget.attrs['placeholder'] = 'First name'
        # self.fields['last_name'].widget.attrs['placeholder'] = 'Last name'
        # self.fields['email'].widget.attrs['placeholder'] = 'Email'
        # self.fields['Phone_number'].widget.attrs['placeholder'] = 'Phone Number'
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'input100'

    
    def clean(self):
        cleaned_data = super(RegisterationFrom, self).clean()
        password = cleaned_data.get('password')
        confirm_password = cleaned_data.get('repeat_password')

        if password != confirm_password:
            raise forms.ValidationError(
                "Password does not match!"
            )
        
      

class UserForm(forms.ModelForm):
    class Meta:
        model = Account
        fields = ('first_name', 'last_name', 'Phone_number')

    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'

class UserProfileForm(forms.ModelForm):
    profile_picture = forms.ImageField(required=False, error_messages = {'invalid':("Image files only")}, widget=forms.FileInput)
    class Meta:
        model = UserProfile
        fields = ('address', 'city', 'state', 'country', 'profile_picture')

    def __init__(self, *args, **kwargs):
        super(UserProfileForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'

accounts/views.py
import requests

from django.shortcuts import render, redirect,get_object_or_404
from django.contrib import messages, auth   
from django.contrib.auth.decorators import login_required

from .forms import RegisterationFrom, UserForm, UserProfileForm
from .models import Account

from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes
from django.utils.encoding import force_str
from django.contrib.auth.tokens import default_token_generator
from django.core.mail import EmailMessage
from .token import account_activation_token
from django.conf import settings
from cart.models import WishlistItem

import uuid

from cart.views import _cart_id
from cart.models import Cart, CartItem
from orders.models import Order
from .models import UserProfile
from orders.models import OrderProduct

def register(request):
    print(request.method)
    if request.method == "POST":
        form = RegisterationFrom(request.POST)
        if form.is_valid():
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            phone_number = form.cleaned_data['Phone_number']
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            username = email.split("@")[0]
            print(first_name, last_name, phone_number)
            user = Account.objects.create_user(first_name=first_name, last_name=last_name, email=email, username=username, password=password)
            user.Phone_number = phone_number
            # user.is_active = True
            user.save()
            
            
            # Create a user profile
            profile = UserProfile()
            profile.user_id = user.id
            # profile.profile_picture = 'default/default-user.png'
            profile.save()

            # USER ACTIVATION


            current_site = get_current_site(request)
            subject = 'Please activate your account'
            message = render_to_string('accounts/email_activate/account_verification_email.html', {
                'user': user,
                'domain': current_site,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': account_activation_token.make_token(user),
            })
            to_email = email
            send_email = EmailMessage(subject=subject,  body=message, to=[to_email] )
            send_email.content_subtype = 'html'


            send_email.send()
            print("EMAIL SENT")
    
            messages.success(request, 'Check Gmail To Active Your Account')

            # return redirect('/account/register/?command=verification&email='+email)

            
            # auth.login(request, user)
            # messages.success(request, 'You Loged in')
            # return redirect('accounts:dashboard')
        else:
            # Print form errors for debugging
            print(form.errors)


    else : # request == GET
        form = RegisterationFrom()

    context = {
        'forms': form,
    }

    return render(request, 'accounts/register.html', context)

def login(request):
    if request.method == "POST":
        email = request.POST['email']
        password = request.POST['password']


        user = auth.authenticate(email=email, password=password)
        print(user)

        if user is not None:
            try:
                cart = Cart.objects.get(cart_id=_cart_id(request))
                is_cart_item_exists = CartItem.objects.filter(cart=cart).exists()
                if is_cart_item_exists:
                    cart_item = CartItem.objects.filter(cart=cart)

                    # Getting the product variations by cart id 
                    product_variation = []
                    for item in cart_item:
                        variation = item.variation.all()
                        product_variation.append(list(variation))

                    # Get the cart items from the user to access his product variations
                    cart_item = CartItem.objects.filter(user=user)
                    ex_var_list = []
                    id = []
                    for item in cart_item:
                        existing_variation = item.variation.all()
                        ex_var_list.append(list(existing_variation))
                        id.append(item.id)

                    for pr in product_variation:
                        if pr in ex_var_list:
                            index = ex_var_list.index(pr)
                            item_id = id[index]
                            item = CartItem.objects.get(id=item_id)
                            item.quantity += 1
                            item.user = user
                            item.save()
                        else:
                            cart_item = CartItem.objects.filter(cart=cart)

                            for item in cart_item:
                                item.user = user
                                item.save()
            except:
                pass

            auth.login(request, user)
            url = request.META.get('HTTP_REFERER')
            try:
                query = requests.utils.urlparse(url).query
                # next=/cart/checkout/
                params = dict(x.split('=') for x in query.split('&'))
                if 'next' in params:
                    nextPage = params['next']
                    return redirect(nextPage)
            except:
                return redirect('accounts:dashboard')
            return redirect('accounts:dashboard')
        else:
            messages.error(request, 'Your email or password is wrong!')
            return redirect('accounts:login')
    return render(request, 'accounts/login.html')


@login_required(login_url = 'accounts:login')
def logout(request):
    auth.logout(request)
    messages.success(request, "You've successfully logged out . Come back soon!")
    return redirect('accounts:login')


def activate(request, uidb64, token):
    try:
        uid = urlsafe_base64_decode(uidb64).decode()
        user = Account._default_manager.get(pk=uid)
    except (TypeError, ValueError, OverflowError, Account.DoesNotExist):
        user = None

    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        messages.success(request, "Your account is activated, log in and let's go.")
        return redirect('accounts:login')
    else:
        messages.error(request, "Invalid activation link, Try again!")
        return redirect('accounts:register')

@login_required(login_url = 'accounts:login')
def dashboard(request):
    orders = Order.objects.order_by('-created_at').filter(user_id=request.user.id, is_ordered=True)
    profile = UserProfile.objects.get(user_id=request.user.id)
    wishlist_items = WishlistItem.objects.filter(user=request.user.id)


    orders_count = orders.count()
    wishlist_count = wishlist_items.count()
    context = {
        'orders':orders,
        'orders_count':orders_count,
        'wishlist_count':wishlist_count,
        'profile':profile,
        'wishlist_items': wishlist_items,
        
    }
    return render(request, 'accounts/dashboard/dashboard.html', context)



@login_required(login_url = 'accounts:login')
def my_orders(request):
    orders = Order.objects.filter(user=request.user, is_ordered=True).order_by('-created_at')
    orders_count = orders.count()
    
    context = {
        'orders':orders,
        'orders_count':orders_count,
    }
    return render(request, 'shop/accounts/dashboard/my_orders.html', context)


@login_required(login_url = 'accounts:login')
def edit_profile(request):
    userprofile = get_object_or_404(UserProfile, user=request.user)
    if request.method == 'POST':
        user_form = UserForm(request.POST, instance=request.user)
        profile_form = UserProfileForm(request.POST, request.FILES, instance=userprofile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, 'Your profile has been updated.')
            return redirect('accounts:edit_profile')
    else:
        user_form = UserForm(instance=request.user)
        profile_form = UserProfileForm(instance=userprofile)
    context = {
        'user_form': user_form,
        'profile_form': profile_form,
        'userprofile': userprofile,
    }
    return render(request, 'accounts/dashboard/profile.html', context)


@login_required(login_url = 'accounts:login')
def change_password(request):
    if request.method == 'POST':
        old_password = request.POST['old_password']
        new_password = request.POST['new_password']
        repeat_new_password = request.POST['repeat_new_password']

        user = Account.objects.get(username__exact=request.user.username)

        if new_password == repeat_new_password:
            success = user.check_password(old_password)
            if success :
                user.set_password(new_password)
                user.save()
                auth.login(request, user)
                messages.success(request, 'Password Updated successfully.')
                return redirect('accounts:change_password')
            else:
                messages.error(request, 'Old password is wrong')
                return redirect('accounts:change_password')
        else:
            messages.error(request, 'Password does not match')
            return redirect('accounts:change_password')
    return render(request, 'accounts/dashboard/change_password.html')


@login_required(login_url = 'accounts:login')
def order_detail(request,order_id):
    order_detail = OrderProduct.objects.filter(order__order_number=order_id)
    order = Order.objects.get(order_number=order_id)

    subtotal = 0

templates/accounts/register.html
{% load static %}


<!DOCTYPE html>
<html lang="en">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="description" content="Fuku Clothings">
    <meta name="keywords" content="Fuku Clothings">
    <meta name="author" content="Fuku Clothings">
    <link rel="icon" href="{% static 'images/favicon/1.png' %}" type="image/x-icon">
    <link rel="shortcut icon" href="{% static 'images/favicon/1.png' %}" type="image/x-icon">
    <title>Fuku clothings</title>

    <!--Google font-->
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,900" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Yellowtail&display=swap" rel="stylesheet">

    <!-- Icons -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/vendors/font-awesome.css' %}">

    <!--Slick slider css-->
    <link rel="stylesheet" type="text/css" href="{% static 'css/vendors/slick.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/vendors/slick-theme.css' %}">

    <!-- Animate icon -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/vendors/animate.css' %}">

    <!-- Themify icon -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/vendors/themify-icons.css' %}">

    <!-- Bootstrap css -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/vendors/bootstrap.css' %}">

    <!-- Theme css -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

</head>


<body class="theme-color-1">


    <!-- header start -->
    {% include "header.html" %}
    <!-- header end -->


    <!-- breadcrumb start -->
    <div class="breadcrumb-section">
        <div class="container">
            <div class="row">
                <div class="col-sm-6">
                    <div class="page-title">
                        <h2>create account</h2>
                    </div>
                </div>
                <div class="col-sm-6">
                    <nav aria-label="breadcrumb" class="theme-breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="/">Home</a></li>
                            <li class="breadcrumb-item active" aria-current="page">create account</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div>
    <!-- breadcrumb End -->


    <!--section start-->
    <section class="register-page section-b-space">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h3>create account</h3>
                    <div class="theme-card">
                        <form class="theme-form" action="{% url 'accounts:register' %}" method="post">
                            {% csrf_token %}


                            {% if forms.errors %}
					
                                <div class="alert alert-danger" role="alert" style="max-width: 100% !important;">
                                <p>Please correct the following errors:</p><br>
                                    {% if forms.email.errors %}
                                    {% for field in forms.email.errors %}
                                        <p><b>Email :</b> {{ field }}</p>
                                    {% endfor %}
                                    {% endif %}

                                    {% if forms.non_field_errors %}
                                    {% for field in forms.non_field_errors %}
                                        <p><b>Password :</b> {{ field }}</p>
                                    {% endfor %}
                                    {% endif %}

                                </div>
                                <br>
                            {% endif %}
                            
                            {% include "includes/alerts.html" %}
                            <div class="form-row row">
                                <div class="col-md-6">
                                    <label for="id_first_name">First Name</label>
                                    <input type="text" class="form-control" id="id_first_name" name="first_name" placeholder="First Name" required>
                                </div>
                                <div class="col-md-6">
                                    <label for="id_last_name">Last Name</label>
                                    <input type="text" class="form-control" id="id_last_name" name="last_name" placeholder="Last Name" required>
                                </div>
                            </div>
                            <div class="form-row row">
                                <div class="col-md-6">
                                    <label for="id_phone_number">Phone Number</label>
                                    <input type="text" class="form-control" id="id_phone_number" name="Phone_number" placeholder="Phone Number" required>
                                </div>
                                <div class="col-md-6">
                                    <label for="id_email">Email</label>
                                    <input type="email" class="form-control" id="id_email" name="email" placeholder="Email" required>
                                </div>
                            </div>
                            <div class="form-row row">
                                <div class="col-md-6">
                                    <label for="id_password">Password</label>
                                    <input type="password" class="form-control" id="id_password" name="password" placeholder="Enter your password" required>
                                </div>
                                <div class="col-md-6">
                                    <label for="id_repeat_password">Confirm Password</label>
                                    <input type="password" class="form-control" id="id_repeat_password" name="repeat_password" placeholder="Confirm Password" required>
                                </div>
                            </div>
                            <div class="form-row row">
                                <div class="col-md-6">
                                    <button type="submit" class="btn btn-solid w-auto">Create Account</button>
                                </div>
                            </div>
                        </form>
                        
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!--Section ends-->


    <!-- footer -->
    {% include "components/footer.html" %}
    <!-- footer end -->


   <!-- theme setting -->
   {% include "components/dark-mode.html" %}
   <!-- theme setting -->

   <!-- latest jquery-->
   <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>

   <!-- fly cart ui jquery-->
   <script src="{% static 'js/jquery-ui.min.js' %}"></script>
   
   <!-- exitintent jquery-->
   <script src="{% static 'js/jquery.exitintent.js' %}"></script>
   <script src="{% static 'js/exit.js' %}"></script>
   
   <!-- slick js-->
   <script src="{% static 'js/slick.js' %}"></script>
   
   <!-- menu js-->
   <script src="{% static 'js/menu.js' %}"></script>
   
   <!-- lazyload js-->
   <script src="{% static 'js/lazysizes.min.js' %}"></script>
   
   <!-- Bootstrap js-->
   <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
   
   <!-- Bootstrap Notification js-->
   <script src="{% static 'js/bootstrap-notify.min.js' %}"></script>
   
   <!-- Fly cart js-->
   <script src="{% static 'js/fly-cart.js' %}"></script>
   
   <!-- Theme js-->
   <script src="{% static 'js/theme-setting.js' %}"></script>
   <script src="{% static 'js/script.js' %}"></script>
   
   <script>
       $(window).on('load', function () {
           setTimeout(function () {
               $('#exampleModal').modal('show');
           }, 2500);
       });
   
       function openSearch() {
           document.getElementById("search-overlay").style.display = "block";
       }
   
       function closeSearch() {
           document.getElementById("search-overlay").style.display = "none";
       }
   </script>
   
   </body>
   
   </html>
   

templates/accounts/send_resetpassword_email.html
{% autoescape off %}

Hi {{user.first_name}},

Please click on below link to reset your password.
http://{{domain}}{% url 'accounts:resetpassword_validate' uidb64=uid token=token %}

{% endautoescape %}