app/urls.py
from django.urls import path
from . import views 

app_name = 'app'

urlpatterns = [
    path('about/', views.about, name='about'),
    path('contact/', views.contact_us, name='contact'),
]

cart/urls.py
from django.urls import path
from . import views 

app_name = 'cart'

urlpatterns = [
    path('', views.cart, name='cart'),
    path('add_cart/<int:product_id>/', views.add_cart, name='add_cart'),
    path('remove_cart/<int:product_id>/<int:cart_item_id>/', views.remove_cart, name='remove_cart'),
    path('remove_cart_item/<int:product_id>/<int:cart_item_id>/', views.remove_cart_item, name='remove_cart_item'),
    path('wishlist/', views.wishlist, name='wishlist'),
    path('wishlist/<int:product_id>/add', views.add_to_wishlist, name='add_to_wishlist'),
    path('wishlist/<int:item_id>/remove/', views.remove_from_wishlist, name='remove_from_wishlist'),

]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls', namespace='shop')),
    path('app/', include('app.urls', namespace='app')),
    path('account/', include('accounts.urls', namespace='accounts')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

orders/urls.py
from django.urls import path
from . import views 

app_name = 'orders'

urlpatterns = [
    path('', views.payment_method, name='payment_method'),
    path('checkout/', views.checkout, name='checkout'),
    path('payment/', views.payment, name='payment'),
    path('payments/', views.payments, name='payments'),
    path('order_completed/', views.order_completed, name='order_complete'),
]

store/urls.py
from django.urls import path
from django.utils.regex_helper import normalize
from . import views


app_name = 'shop'

urlpatterns = [
    path('', views.home, name='home'),
    path('shop/', views.shop, name='shop'),
    path('shop/<slug:category_slug>/', views.shop, name='categries'),
    path('shop/<slug:category_slug>/<slug:product_details_slug>/', views.product_details, name='product_details'),
    path('search/', views.search, name='search'),
    path('review/<int:product_id>/', views.review, name='review'),
]

cart/models.py
from django.db import models

from store.models import Product, Variation
from accounts.models import Account

class Cart(models.Model):
    cart_id = models.CharField(max_length=250, blank=True)
    create = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.cart_id


class CartItem(models.Model):
    user = models.ForeignKey(Account, on_delete=models.CASCADE, null=True )
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variation = models.ManyToManyField(Variation, blank=True)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, null=True)
    quantity = models.IntegerField()
    is_active = models.BooleanField(default=True)

    def sub_total(self):
        return self.product.selling_price * self.quantity

    def __unicode__(self):
        return self.product


class WishlistItem(models.Model):
    user = models.ForeignKey(Account, on_delete=models.CASCADE, null=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variation = models.ManyToManyField(Variation, blank=True)

    def __str__(self):
        return f"{self.product.name} - Wishlist"

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .models import Cart, CartItem
from store.models import Product, Variation


def _cart_id(request):
    cart = request.session.session_key
    if not cart :
        cart = request.session.create()
    return cart
#s

def add_cart(request, product_id):
    current_user = request.user
    product = Product.objects.get(id=product_id) # get the product
    product_variation = []
    if current_user.is_authenticated:
        product_variation = []
        if request.method == 'POST':
            for item in request.POST :
                key = item
                value = request.POST[key]
                try:
                    variation = Variation.objects.get(product=product, variation_category__iexact=key, variation_value__iexact=value)
                    product_variation.append(variation)
                except:
                    pass
        is_cart_item_exist = CartItem.objects.filter(product=product, user=current_user).exists()
        if is_cart_item_exist:
            cart_item = CartItem.objects.filter(product=product, user=current_user)
            ex_var_list = []
            id = []
            for item in cart_item:
                existing_variation = item.variation.all()
                ex_var_list.append(list(existing_variation))
                id.append(item.id)

            if product_variation in ex_var_list:
                # increase the cart item quantity
                index = ex_var_list.index(product_variation)
                item_id = id[index]
                item = CartItem.objects.get(product=product, id=item_id)
                item.quantity += 1
                item.save()
            else:
                item = CartItem.objects.create(product=product, quantity=1, user=current_user)
                if len(product_variation) > 0 :
                    item.variation.clear()
                    item.variation.add(*product_variation)
                item.save()

        else:
            cart_item = CartItem.objects.create(
                product=product,
                quantity = 1,
                user = current_user,
            )
            if len(product_variation) > 0 :
                cart_item.variation.clear()
                cart_item.variation.add(*product_variation)
            cart_item.save()

        return redirect('cart:cart')

    # if the user is not authencated
    else:        

        if request.method == 'POST':
            for item in request.POST :
                key = item
                value = request.POST[key]
                try:
                    variation = Variation.objects.get(product=product, variation_category__iexact=key, variation_value__iexact=value)
                    product_variation.append(variation)
                except:
                    pass

        try:
            cart = Cart.objects.get(cart_id=_cart_id(request)) # get the cart using the cart_id present in the session
        except Cart.DoesNotExist:
            cart = Cart.objects.create(cart_id=_cart_id(request))

        cart.save()

        is_cart_item_exist = CartItem.objects.filter(product=product, cart=cart).exists()
        if is_cart_item_exist:
            cart_item = CartItem.objects.filter(product=product, cart=cart)
            ex_var_list = []
            id = []
            for item in cart_item:
                existing_variation = item.variation.all()
                ex_var_list.append(list(existing_variation))
                id.append(item.id)

            if product_variation in ex_var_list:
                # increase the cart item quantity
                index = ex_var_list.index(product_variation)
                item_id = id[index]
                item = CartItem.objects.get(product=product, id=item_id)
                item.quantity += 1
                item.save()
            else:
                item = CartItem.objects.create(product=product, quantity=1, cart=cart)
                if len(product_variation) > 0 :
                    item.variation.clear()
                    item.variation.add(*product_variation)
                item.save()

        else:
            cart_item = CartItem.objects.create(
                product=product,
                quantity = 1,
                cart=cart,
            )
            if len(product_variation) > 0 :
                cart_item.variation.clear()
                cart_item.variation.add(*product_variation)
            cart_item.save()

        return redirect('cart:cart')

def remove_cart(request, product_id, cart_item_id):
    product = get_object_or_404(Product, id=product_id)
    try:
        if request.user.is_authenticated:
            cart_item = CartItem.objects.get(product=product, user=request.user, id=cart_item_id)
        else:
            cart = Cart.objects.get(cart_id=_cart_id(request))
            cart_item = CartItem.objects.get(product=product, cart=cart, id=cart_item_id)
        if cart_item.quantity > 1 :
            cart_item.quantity -= 1
            cart_item.save()
        else :
            cart_item.delete()
    except:
        pass

    return redirect('cart:cart')


def remove_cart_item(request, product_id, cart_item_id):
    product = get_object_or_404(Product, id=product_id)
    if request.user.is_authenticated:
        cart_item = CartItem.objects.get(product=product, user=request.user, id=cart_item_id)
    else:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_item = CartItem.objects.get(product=product, cart=cart, id=cart_item_id)
    cart_item.delete()
    return redirect('cart:cart')

def cart(request, total_price=0, quantity=0, cart_items=None):
    grand_total = 0
    tax = 0

    try:
        if request.user.is_authenticated:
            cart_items = CartItem.objects.filter(user=request.user, is_active=True)
        else:
            cart = Cart.objects.get(cart_id=_cart_id(request))
            cart_items = CartItem.objects.filter(cart=cart, is_active=True)
        for cart_item in cart_items:
            total_price += (cart_item.product.selling_price * cart_item.quantity)
            quantity += cart_item.quantity
    
    except ObjectDoesNotExist:
        pass
    
    
    tax = round(((2 * total_price)/100), 2)
    grand_total = total_price + tax
    handing = 15.00
    total = float(grand_total) + handing

    context = {
        'total' : total_price,
        'quantity': quantity,
        'cart_items':cart_items,
        'order_total':total,
        'vat' : tax,
        'handing':handing,
    }

    return render(request, 'shop/cart.html', context)





from django.shortcuts import render, redirect, get_object_or_404
from .models import WishlistItem
from store.models import Product, Variation
from django.contrib import messages

def add_to_wishlist(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    user = request.user
    if user.is_authenticated:
        product_variation = []
        if request.method == 'POST':
            for item in request.POST:
                key = item
                value = request.POST[key]
                try:
                    variation = Variation.objects.get(product=product, variation_category__iexact=key, variation_value__iexact=value)
                    product_variation.append(variation)
                except:
                    pass
        wishlist_item, created = WishlistItem.objects.get_or_create(
            user=user,
            product=product
        )
        if created:
            # If the item is added to the wishlist for the first time
            wishlist_item.variation.set(product_variation)
            wishlist_item.save()
            messages.success(request, f"{product.name} has been added to your wishlist.")
        else:
            # If the item is already in the wishlist
            messages.info(request, f"{product.name} is already in your wishlist.")
        return redirect('cart:wishlist')
    else:
        # Redirect to login page if user is not authenticated
        return redirect('accounts:login')

def wishlist(request):
    user = request.user
    if user.is_authenticated:
        wishlist_items = WishlistItem.objects.filter(user=user)
        context = {
            'wishlist_items': wishlist_items
        }
        return render(request, 'shop/wishlist.html', context)
    else:
        # Redirect to login page if user is not authenticated
        return redirect('accounts:login')

def remove_from_wishlist(request, item_id):
    wishlist_item = get_object_or_404(WishlistItem, id=item_id)
    user = request.user
    if user.is_authenticated and wishlist_item.user == user:
        product_name = wishlist_item.product.name
        wishlist_item.delete()
        messages.success(request, f"{product_name} has been removed from your wishlist.")
        return redirect('cart:wishlist')
    else:
        # Redirect to login page if user is not authenticated or doesn't own the wishlist item
        return redirect('accounts:login')

templates/shop/wishlist.html
{% load static %}


<!DOCTYPE html>
<html lang="en">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="description" content="Fuku Clothings">
    <meta name="keywords" content="Fuku Clothings">
    <meta name="author" content="Fuku Clothings">
    <link rel="icon" href="{% static 'images/favicon/1.png' %}" type="image/x-icon">
    <link rel="shortcut icon" href="{% static 'images/favicon/1.png' %}" type="image/x-icon">
    <title>Fuku clothings</title>

    <!--Google font-->
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,900" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Yellowtail&display=swap" rel="stylesheet">

    <!-- Icons -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/vendors/font-awesome.css' %}">

    <!--Slick slider css-->
    <link rel="stylesheet" type="text/css" href="{% static 'css/vendors/slick.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/vendors/slick-theme.css' %}">

    <!-- Animate icon -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/vendors/animate.css' %}">

    <!-- Themify icon -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/vendors/themify-icons.css' %}">

    <!-- Bootstrap css -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/vendors/bootstrap.css' %}">

    <!-- Theme css -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

</head>


<body class="theme-color-1">

    <!-- header start -->
    {% include "header.html" %}
    <!-- header end -->


    <!-- breadcrumb start -->
    <div class="breadcrumb-section">
        <div class="container">
            <div class="row">
                <div class="col-sm-6">
                    <div class="page-title">
                        <h2>wishlist</h2>
                    </div>
                </div>
                <div class="col-sm-6">
                    <nav aria-label="breadcrumb" class="theme-breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="/">Home</a></li>
                            <li class="breadcrumb-item active">wishlist</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div>
    <!-- breadcrumb End -->


    <!--section start-->
    <section class="wishlist-section section-b-space">
        <div class="container">
            <div class="row">
                <div class="col-sm-12 table-responsive-xs" style="overflow:scroll">
                    <table class="table cart-table">
                        <thead>
                            <tr class="table-head">
                                <th scope="col">Image</th>
                                <th scope="col">Product Name</th>
                                <th scope="col" style="display: table-cell;">Price</th>
                                <th scope="col" style="display: table-cell;">Availability</th>
                                <th scope="col" style="display: table-cell;">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% if wishlist_items %}

                            {% for item in wishlist_items %}
                            <tr>
                                <td style="min-width:100%;">
                                    <a href="#"><img src="{{ item.product.image.url }}" alt="{{ item.product.name }}"></a>
                                </td>
                                <td style="display: table-cell;min-width: 100%;">
                                    <a href="#">{{ item.product.name }}</a> {% if item.variation.all %}
                                    {% for variant in item.variation.all %}
                                    <p>{{variant.variation_category | capfirst}} : {{variant.variation_value | capfirst}}</p>
                                    {% endfor %}
                                {% endif %} 
                                    {% comment %} <div class="mobile-cart-content row">
                                        <div class="col">
                                            <p>{% if item.product.is_available %}In Stock{% else %}Out of Stock{% endif %}</p>
                                        </div>
                                        <div class="col">
                                            <h2 class="td-color">₹{{ item.product.price }}</h2>
                                        </div>
                                        <div class="col">
                                            <h2 class="td-color">
                                                <a href="{% url 'cart:remove_from_wishlist' item.id %}" class="icon me-1"><i class="ti-close"></i></a>
                                                <a href="{% url 'cart:add_cart' item.product.id %}" class="cart"><i class="ti-shopping-cart"></i></a>
                                            </h2>
                                        </div>
                                    </div> {% endcomment %}
                                </td>
                                <td style="display: table-cell;min-width: 100%;">
                                    <h2>₹{{ item.product.price }}</h2>
                                </td>
                                <td style="display: table-cell;min-width: 100%;">
                                    <p>{% if item.product.is_available %}In Stock{% else %}Out of Stock{% endif %}</p>
                                </td>
                                <td style="display: table-cell;min-width: 100%;">
                                    <a href="{% url 'cart:remove_from_wishlist' item.id %}" class="icon me-3"><i class="ti-close"></i></a>
                                    <a href="{% url 'cart:add_cart' item.product.id %}" class="cart"><i class="ti-shopping-cart"></i></a>
                                </td>
                            </tr>
                            {% endfor %}
                            {% else %}
                                <tr>
                                    <td colspan="5">No products available in the wishlist.</td>
                                </tr>
                            {% endif %}
                        </tbody>
                    </table>
                    
                </div>
            </div>
            <div class="row wishlist-buttons">
                <div class="col-12"><a href="{% url "shop:shop" %}" class="btn btn-solid">continue shopping</a> <a href="{% url "orders:checkout" %}"
                        class="btn btn-solid">check out</a></div>
            </div>
        </div>
    </section>
    <!--section end-->


    <!-- footer -->
    {% include "components/footer.html" %}
    <!-- footer end -->


    <!-- theme setting -->
    {% include "components/dark-mode.html" %}
    <!-- theme setting -->



    <!-- tap to top start -->
    <div class="tap-top">
        <div><i class="fa fa-angle-double-up"></i></div>
    </div>
    <!-- tap to top end -->



   <!-- latest jquery-->
   <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>

   <!-- fly cart ui jquery-->
   <script src="{% static 'js/jquery-ui.min.js' %}"></script>
   
   <!-- exitintent jquery-->
   <script src="{% static 'js/jquery.exitintent.js' %}"></script>
   <script src="{% static 'js/exit.js' %}"></script>
   
   <!-- slick js-->
   <script src="{% static 'js/slick.js' %}"></script>
   
   <!-- menu js-->
   <script src="{% static 'js/menu.js' %}"></script>
   
   <!-- lazyload js-->
   <script src="{% static 'js/lazysizes.min.js' %}"></script>
   
   <!-- Bootstrap js-->
   <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
   
   <!-- Bootstrap Notification js-->
   <script src="{% static 'js/bootstrap-notify.min.js' %}"></script>
   
   <!-- Fly cart js-->
   <script src="{% static 'js/fly-cart.js' %}"></script>
   
   <!-- Theme js-->
   <script src="{% static 'js/theme-setting.js' %}"></script>
   <script src="{% static 'js/script.js' %}"></script>
   
   <script>
       $(window).on('load', function () {
           setTimeout(function () {
               $('#exampleModal').modal('show');
           }, 2500);
       });
   
       function openSearch() {
           document.getElementById("search-overlay").style.display = "block";
       }
   
       function closeSearch() {
           document.getElementById("search-overlay").style.display = "none";
       }
   </script>
   
   </body>
   
   </html>
   