accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),

    path('', views.dashboard, name='dashboard'),
    # path('my_orders/', views.my_orders, name='my_orders'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('change_password/', views.change_password, name='change_password'),
    path('order_detail/<int:order_id>/', views.order_detail, name='order_detail'),
    
    path('forget_password/', views.forget_password, name="forget_password"),
    path('resetpassword_validate/<uidb64>/<token>/', views.resetpassword_validate, name='resetpassword_validate'),
    path('reset_password/', views.reset_password, name="reset_password"),
]

app/urls.py
from django.urls import path
from . import views 

app_name = 'app'

urlpatterns = [
    path('about/', views.about, name='about'),
    path('contact/', views.contact_us, name='contact'),
]

cart/urls.py
from django.urls import path
from . import views 

app_name = 'cart'

urlpatterns = [
    path('', views.cart, name='cart'),
    path('add_cart/<int:product_id>/', views.add_cart, name='add_cart'),
    path('remove_cart/<int:product_id>/<int:cart_item_id>/', views.remove_cart, name='remove_cart'),
    path('remove_cart_item/<int:product_id>/<int:cart_item_id>/', views.remove_cart_item, name='remove_cart_item'),
    path('wishlist/', views.wishlist, name='wishlist'),
    path('wishlist/<int:product_id>/add', views.add_to_wishlist, name='add_to_wishlist'),
    path('wishlist/<int:item_id>/remove/', views.remove_from_wishlist, name='remove_from_wishlist'),

]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls', namespace='shop')),
    path('app/', include('app.urls', namespace='app')),
    path('account/', include('accounts.urls', namespace='accounts')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

orders/urls.py
from django.urls import path
from . import views 

app_name = 'orders'

urlpatterns = [
    path('', views.payment_method, name='payment_method'),
    path('checkout/', views.checkout, name='checkout'),
    path('payment/', views.payment, name='payment'),
    path('payments/', views.payments, name='payments'),
    path('order_completed/', views.order_completed, name='order_complete'),
]

store/urls.py
from django.urls import path
from django.utils.regex_helper import normalize
from . import views


app_name = 'shop'

urlpatterns = [
    path('', views.home, name='home'),
    path('shop/', views.shop, name='shop'),
    path('shop/<slug:category_slug>/', views.shop, name='categries'),
    path('shop/<slug:category_slug>/<slug:product_details_slug>/', views.product_details, name='product_details'),
    path('search/', views.search, name='search'),
    path('review/<int:product_id>/', views.review, name='review'),
]

templates/base.html
{% load static %}


<!DOCTYPE html>
<html lang="en">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="description" content="Fuku Clothings">
    <meta name="keywords" content="Fuku Clothings">
    <meta name="author" content="Fuku Clothings">
    <link rel="icon" href="{% static 'images/favicon/1.png' %}" type="image/x-icon">
    <link rel="shortcut icon" href="{% static 'images/favicon/1.png' %}" type="image/x-icon">
    <title>Fuku - E-commerce</title>

    <!--Google font-->
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,900" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Yellowtail&display=swap" rel="stylesheet">

    <!-- Icons -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/vendors/font-awesome.css' %}">

    <!--Slick slider css-->
    <link rel="stylesheet" type="text/css" href="{% static 'css/vendors/slick.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/vendors/slick-theme.css' %}">

    <!-- Animate icon -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/vendors/animate.css' %}">

    <!-- Themify icon -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/vendors/themify-icons.css' %}">

    <!-- Bootstrap css -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/vendors/bootstrap.css' %}">

    <!-- Theme css -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

</head>


{% block content %}

{% endblock content %}



   <!-- latest jquery-->
   <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>

   <!-- fly cart ui jquery-->
   <script src="{% static 'js/jquery-ui.min.js' %}"></script>
   
   <!-- exitintent jquery-->
   <script src="{% static 'js/jquery.exitintent.js' %}"></script>
   <script src="{% static 'js/exit.js' %}"></script>
   
   <!-- slick js-->
   <script src="{% static 'js/slick.js' %}"></script>
   
   <!-- menu js-->
   <script src="{% static 'js/menu.js' %}"></script>
   
   <!-- lazyload js-->
   <script src="{% static 'js/lazysizes.min.js' %}"></script>
   
   <!-- Bootstrap js-->
   <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
   
   <!-- Bootstrap Notification js-->
   <script src="{% static 'js/bootstrap-notify.min.js' %}"></script>
   
   <!-- Fly cart js-->
   <script src="{% static 'js/fly-cart.js' %}"></script>
   
   <!-- Theme js-->
   <script src="{% static 'js/theme-setting.js' %}"></script>
   <script src="{% static 'js/script.js' %}"></script>
   
   <script>
       $(window).on('load', function () {
           setTimeout(function () {
               $('#exampleModal').modal('show');
           }, 2500);
       });
   
       function openSearch() {
           document.getElementById("search-overlay").style.display = "block";
       }
   
       function closeSearch() {
           document.getElementById("search-overlay").style.display = "none";
       }
   </script>
   
   </body>
   
   </html>
   

templates/coming_soon.html
{% load static %}


<!DOCTYPE html>
<html lang="en">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="description" content="Fuku">
    <meta name="keywords" content="Fuku">
    <meta name="author" content="Fuku">
    <link rel="icon" href="{% static 'images/favicon/1.png' %}" type="image/x-icon">
    <link rel="shortcut icon" href="{% static 'images/favicon/1.png' %}" type="image/x-icon">
    <title>Fuku Clothings </title>

    <!--Google font-->
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,900" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Yellowtail&display=swap" rel="stylesheet">

    <!-- Icons -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/vendors/font-awesome.css' %}">

    <!--Slick slider css-->
    <link rel="stylesheet" type="text/css" href="{% static 'css/vendors/slick.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/vendors/slick-theme.css' %}">

    <!-- Animate icon -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/vendors/animate.css' %}">

    <!-- Themify icon -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/vendors/themify-icons.css' %}">

    <!-- Bootstrap css -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/vendors/bootstrap.css' %}">

    <!-- Theme css -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

</head>


<body class="theme-color-1">


    <div class="template-password">
        <div class="container">
            <div id="container" class="text-center">
                <div>
                    <div id="login">
                        <div>
                            <div class="logo mb-4">
                                <a href="#">
                                    <img  src="{% static 'images/icon/FUKU1.png' %}" alt="Fuku Fashions" class="img-fluid" style="height:70px">
                                </a>
                            </div>
                            <h2 class="mb-3">
                                Will be Opening Soon!
                            </h2>
                        </div>
                        <div class="row">
                            <div class="col-sm-12">
                                <form action="#" class="theme-form">
                                    <div class="col-md-12 mt-2">
                                        <h3>Enter Your Email: </h3>
                                    </div>
                                    <div class="form-row row">
                                        <div class="col-md-12">
                                            <input type="password" name="password" id="password" class="form-control"
                                                autofocus="">
                                        </div>
                                        <div class="col-md-12">
                                            <div class="actions">
                                                <button type="submit" class="btn btn-solid">notify me</button>
                                            </div>
                                        </div>
                                    </div>

                                </form>
                            </div>
                        </div>
                        <div id="footer" class="mt-4">
                            {% comment %} <div id="owner">
                                Are you the store owner? <a href="#">Log in here</a> or <a href="#">change your password
                                    settings</a>
                            </div> {% endcomment %}
                        </div>
                    </div>
                    <div id="powered">
                        <p>© 2024, Powered by FUKU.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>


    
   <!-- latest jquery-->
<script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>

<!-- fly cart ui jquery-->
<script src="{% static 'js/jquery-ui.min.js' %}"></script>

<!-- exitintent jquery-->
<script src="{% static 'js/jquery.exitintent.js' %}"></script>
<script src="{% static 'js/exit.js' %}"></script>

<!-- slick js-->
<script src="{% static 'js/slick.js' %}"></script>

<!-- menu js-->
<script src="{% static 'js/menu.js' %}"></script>

<!-- lazyload js-->
<script src="{% static 'js/lazysizes.min.js' %}"></script>

<!-- Bootstrap js-->
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>

<!-- Bootstrap Notification js-->
<script src="{% static 'js/bootstrap-notify.min.js' %}"></script>

<!-- Fly cart js-->
<script src="{% static 'js/fly-cart.js' %}"></script>

<!-- Theme js-->
<script src="{% static 'js/theme-setting.js' %}"></script>
<script src="{% static 'js/script.js' %}"></script>

<script>
    $(window).on('load', function () {
        setTimeout(function () {
            $('#exampleModal').modal('show');
        }, 2500);
    });

    function openSearch() {
        document.getElementById("search-overlay").style.display = "block";
    }

    function closeSearch() {
        document.getElementById("search-overlay").style.display = "none";
    }
</script>

</body>

</html>

templates/header.html
{% load static %}
<!-- header start -->
    <header>
        <div class="mobile-fix-option"></div>
        <div class="top-header">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6">
                        <div class="header-contact">
                            <ul>
                                <li>Welcome to Fuku Clothings</li>
                                <li><i class="fa fa-phone" aria-hidden="true"></i>Call Us: 7470385398</li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-lg-6 text-end">
                        <ul class="header-dropdown">
                            <li class="mobile-wishlist"><a href="{% url 'cart:wishlist' %}"><i class="fa fa-heart" aria-hidden="true"></i></a>
                            </li>
                            <li class="onhover-dropdown mobile-account"> <i class="fa fa-user" aria-hidden="true"></i>
                                My Account
                                <ul class="onhover-show-div">
                                    {% if user.is_authenticated %}
                                    <li><a href="{% url 'accounts:dashboard' %}">Dashboard</a> </li>
                                    <li><a href="{% url 'accounts:logout' %}">Log Out</a> </li>
                                    {% else %}
                                    <li><a href="{% url 'accounts:login' %}">Login</a></li>
                                    <li><a href="{% url 'accounts:register' %}">register</a></li>
                                    {% endif %}
                                </ul>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                    <div class="main-menu">
                        <div class="menu-left">

                            <div class="brand-logo">
                                <a href="{% url 'shop:home' %}"><img src="{% static 'images/icon/FUKU.png' %}"
                                        class="img-fluid blur-up lazyload" alt="" style="height:40px"></a>
                            </div>
                        </div>
                        <div class="menu-right pull-right">
                            <div>
                                <nav id="main-nav">
                                    <div class="toggle-nav"><i class="fa fa-bars sidebar-bar"></i></div>
                                    <ul id="main-menu" class="sm pixelstrap sm-horizontal">
                                        <li>
                                            <div class="mobile-back text-end">Back<i class="fa fa-angle-right ps-2"
                                                aria-hidden="true"></i></div>
                                            </li>

                                        <li><a href="#">Custom Tees</a> </li>

                                        <li>
                                            <a href="{% url 'shop:shop' %}">T-shirts <div class="lable-nav">new</div></a>
                                            <ul>
                                                <li><a href="{% url 'shop:shop' %}">All</a></li>
                                                {% for category in categories %}
                                                <li><a href="{{ category.get_category_slug_url }}">{{category.name}} <span class="new-tag">new</span></a> </li>
                                                {% endfor %}
                                            </ul>
                                        </li>
                                        <li>
                                            <a href="#">Information</a>
                                            <ul>
                                                <li><a href="{% url 'app:about' %}">About Us</a></li>
                                                <li> <a href="https://www.linkedin.com/company/fuku-company/" target="_blank">Community</a></li>

                                            </ul>
                                        </li>
                                        <li><a href="#">Track order</a>
                                            
                                        </li>
                                    </ul>
                                </nav>
                            </div>
                            <div>
                                <div class="icon-nav">
                                    <ul>
                                        <li class="onhover-div mobile-search">
                                            <div><img src="{% static 'images/icon/search.png' %}" onclick="openSearch()"
                                                    class="img-fluid blur-up lazyload" alt=""> <i class="ti-search"
                                                    onclick="openSearch()"></i></div>
                                            <div id="search-overlay" class="search-overlay">
                                                <div> <span class="closebtn" onclick="closeSearch()"
                                                        title="Close Overlay">×</span>
                                                    <div class="overlay-content">
                                                        <div class="container">
                                                            <div class="row">
                                                                <div class="col-xl-12">
                                                                    <form  action={% url 'shop:search' %} method="GET">
                                                                        <div class="form-group">
                                                                            <input type="text" class="form-control"
                                                                                id="exampleInputPassword1" name="keyword"
                                                                                placeholder="Search a Product......">
                                                                                <button type="submit" class="btn btn-primary"><i
                                                                                        class="fa fa-search"></i>Search</button>
                                                                        </div>
                                                                    </form>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </li>
                                        {% comment %} <li class="onhover-div mobile-wishlist"><a href="{% url 'cart:wishlist' %}"><img
                                            src="{% static 'images/icon/heart-1.png' %}" alt=""></a>
                                        </li> {% endcomment %}
                                        
                                        
                                        <li class="onhover-div mobile-cart">
                                            <div><a href="{% url 'cart:cart' %}"><img src="{% static 'images/icon/cart.png' %}"
                                                class="img-fluid blur-up lazyload" alt=""> </a><i
                                                class="ti-shopping-cart"></i></div>
                                                <span class="cart_qty_cls">{{quantityyy}}</span>
                                                <ul class="show-div shopping-cart">
                                                {% for x in cart_itemsss %}
                                                <li>
                                                    <div class="media">
                                                        <a href="{{x.product.get_prodcut_details_url}}"><img alt="" class="me-3"
                                                                src="{{x.product.image.url}}"></a>
                                                        <div class="media-body">
                                                            <a href="{{x.product.get_prodcut_details_url}}">
                                                                <h4>{{x.product.name}}</h4>
                                                            </a>
                                                            <h4><span>{{x.quantity}} x ₹ {{x.product.selling_price}}</span></h4>
                                                        </div>
                                                    </div>
                                                    <div class="close-circle"><a href="{% url 'cart:remove_cart_item' x.product.id x.id %}"><i class="fa fa-times"
                                                                aria-hidden="true"></i></a></div>
                                                </li>
                                                {% endfor %}


                                                <li>
                                                    <div class="total">
                                                        <h5>subtotal : <span>₹{{totalll}}</span></h5>
                                                    </div>
                                                </li>
                                                <li>
                                                    <div class="buttons"><a href="{% url "cart:cart" %}" class="view-cart">view
                                                            cart</a> <a href="{% url "orders:checkout" %}" class="checkout">checkout</a></div>
                                                </li>
                                            </ul>
                                        </li>
                                        <li class="onhover-div mobile-setting">
                                            <div><img src="{% static 'images/icon/setting.png' %}"
                                                    class="img-fluid blur-up lazyload" alt=""> <i
                                                    class="ti-settings"></i></div>
                                            <div class="show-div setting">
                                                {% if user.is_authenticated %}
                                                <h6>Account</h6>
                                                <ul>
                                                    <li><a href="{% url 'accounts:dashboard' %}">Profile</a></li>
                                                    <li><a href="{% url 'accounts:dashboard' %}">Orders</a></li>
                                                </ul>
                                                {% endif %}
                                                <h6>Information</h6>
                                                <ul class="list-inline">
                                                    <li><a href="{% url 'app:about' %}">About us</a></li>
                                                    <li><a href="#">Contact Us</a></li>
                                                    <li><a href="https://www.linkedin.com/company/fuku-company/" target="_blank">Community</a></li>
                                                </ul>
                                            </div>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <!-- header end -->